spring:
  application:
    name: account-service
    
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    show-sql: true

server:
  port: 8081
