spring:
  application:
    name: account-service

  datasource:
    url: ${vault.db.url}
    username: ${vault.db.username}
    password: ${vault.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    show-sql: true

server:
  port: 8081
